GET http://localhost:3000/api/notes


###
POST http://localhost:3000/api/notes
content-type: application/json

{
    "title":"fresh note","content":"This is a fresh note"
}

###

PUT  http://localhost:3000/api/notes/a1d0d14c-a8b6-4d85-be1b-4c0b8ef3c98f
content-type: application/json

{
    "title":"this note was updated 5","content":"the content updated"
}

###
DELETE  http://localhost:3000/api/notes/518f558b-9bcb-4adc-8d34-60abe973f7e2